---
 - name: start services
   hosts: localhost

   tasks:
     - name: Terraform Plan the destruction
       shell: chdir=/home/myroslav/final_task/4bigdata/k8s terraform plan -destroy -out destroyplan

     - name: Terraform Destroy
       shell: chdir=/home/myroslav/final_task/4bigdata/k8s terraform apply destroyplan
