---
 - name: start services
   hosts: localhost

   tasks:
     - name: Terraform Plan the destruction
       shell: chdir=./k8s terraform plan -destroy -out destroyplan

     - name: Terraform Destroy
       shell: chdir=./k8s terraform apply destroyplan
